apiVersion: kustomize.factory.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- argo-mysql-config-secret.yaml
- mysql-deployment.yaml
- mysql-service.yaml
patches:
- path: overlays/workflow-controller-configmap.yaml
