apiVersion: kustomize.factory.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow

resources:
- cache-cert-issuer.yaml
- cache-cert.yaml
- cache-webhook-factory.yaml

configurations:
- params.yaml
labels:
- includeSelectors: true
  pairs:
    app: cache-server-cert-manager
