// Copyright 2025 The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: backend/api/v2beta1/artifact.proto

package go_client

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArtifactTaskType int32

const (
	ArtifactTaskType_INPUT  ArtifactTaskType = 0
	ArtifactTaskType_OUTPUT ArtifactTaskType = 1
)

// Enum value maps for ArtifactTaskType.
var (
	ArtifactTaskType_name = map[int32]string{
		0: "INPUT",
		1: "OUTPUT",
	}
	ArtifactTaskType_value = map[string]int32{
		"INPUT":  0,
		"OUTPUT": 1,
	}
)

func (x ArtifactTaskType) Enum() *ArtifactTaskType {
	p := new(ArtifactTaskType)
	*p = x
	return p
}

func (x ArtifactTaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArtifactTaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_backend_api_v2beta1_artifact_proto_enumTypes[0].Descriptor()
}

func (ArtifactTaskType) Type() protoreflect.EnumType {
	return &file_backend_api_v2beta1_artifact_proto_enumTypes[0]
}

func (x ArtifactTaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArtifactTaskType.Descriptor instead.
func (ArtifactTaskType) EnumDescriptor() ([]byte, []int) {
	return file_backend_api_v2beta1_artifact_proto_rawDescGZIP(), []int{0}
}

type MetricType int32

const (
	MetricType_METRIC_INPUT  MetricType = 0
	MetricType_METRIC_OUTPUT MetricType = 1
)

// Enum value maps for MetricType.
var (
	MetricType_name = map[int32]string{
		0: "METRIC_INPUT",
		1: "METRIC_OUTPUT",
	}
	MetricType_value = map[string]int32{
		"METRIC_INPUT":  0,
		"METRIC_OUTPUT": 1,
	}
)

func (x MetricType) Enum() *MetricType {
	p := new(MetricType)
	*p = x
	return p
}

func (x MetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_backend_api_v2beta1_artifact_proto_enumTypes[1].Descriptor()
}

func (MetricType) Type() protoreflect.EnumType {
	return &file_backend_api_v2beta1_artifact_proto_enumTypes[1]
}

func (x MetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricType.Descriptor instead.
func (MetricType) EnumDescriptor() ([]byte, []int) {
	return file_backend_api_v2beta1_artifact_proto_rawDescGZIP(), []int{1}
}

// Required. Schema of the metric
type Metric_Schema int32

const (
	Metric_Metric                     Metric_Schema = 0
	Metric_ClassificationMetric       Metric_Schema = 1
	Metric_SlicedClassificationMetric Metric_Schema = 2
)

// Enum value maps for Metric_Schema.
var (
	Metric_Schema_name = map[int32]string{
		0: "Metric",
		1: "ClassificationMetric",
		2: "SlicedClassificationMetric",
	}
	Metric_Schema_value = map[string]int32{
		"Metric":                     0,
		"ClassificationMetric":       1,
		"SlicedClassificationMetric": 2,
	}
)

func (x Metric_Schema) Enum() *Metric_Schema {
	p := new(Metric_Schema)
	*p = x
	return p
}

func (x Metric_Schema) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Metric_Schema) Descriptor() protoreflect.EnumDescriptor {
	return file_backend_api_v2beta1_artifact_proto_enumTypes[2].Descriptor()
}

func (Metric_Schema) Type() protoreflect.EnumType {
	return &file_backend_api_v2beta1_artifact_proto_enumTypes[2]
}

func (x Metric_Schema) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Metric_Schema.Descriptor instead.
func (Metric_Schema) EnumDescriptor() ([]byte, []int) {
	return file_backend_api_v2beta1_artifact_proto_rawDescGZIP(), []int{13, 0}
}

type Artifact_ArtifactType int32

const (
	Artifact_Artifact Artifact_ArtifactType = 0
	Artifact_Model    Artifact_ArtifactType = 1
	Artifact_Dataset  Artifact_ArtifactType = 2
	Artifact_HTML     Artifact_ArtifactType = 3
	Artifact_Markdown Artifact_ArtifactType = 4
)

// Enum value maps for Artifact_ArtifactType.
var (
	Artifact_ArtifactType_name = map[int32]string{
		0: "Artifact",
		1: "Model",
		2: "Dataset",
		3: "HTML",
		4: "Markdown",
	}
	Artifact_ArtifactType_value = map[string]int32{
		"Artifact": 0,
		"Model":    1,
		"Dataset":  2,
		"HTML":     3,
		"Markdown": 4,
	}
)

func (x Artifact_ArtifactType) Enum() *Artifact_ArtifactType {
	p := new(Artifact_ArtifactType)
	*p = x
	return p
}

func (x Artifact_ArtifactType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Artifact_ArtifactType) Descriptor() protoreflect.EnumDescriptor {
	return file_backend_api_v2beta1_artifact_proto_enumTypes[3].Descriptor()
}

func (Artifact_ArtifactType) Type() protoreflect.EnumType {
	return &file_backend_api_v2beta1_artifact_proto_enumTypes[3]
}

func (x Artifact_ArtifactType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Artifact_ArtifactType.Descriptor instead.
func (Artifact_ArtifactType) EnumDescriptor() ([]byte, []int) {
	return file_backend_api_v2beta1_artifact_proto_rawDescGZIP(), []int{14, 0}
}

type CreateArtifactRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The artifact to create.
	Artifact      *Artifact `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArtifactRequest) Reset() {
	*x = CreateArtifactRequest{}
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArtifactRequest) ProtoMessage() {}

func (x *CreateArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArtifactRequest.ProtoReflect.Descriptor instead.
func (*CreateArtifactRequest) Descriptor() ([]byte, []int) {
	return file_backend_api_v2beta1_artifact_proto_rawDescGZIP(), []int{0}
}

func (x *CreateArtifactRequest) GetArtifact() *Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

type UpdateArtifactRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The artifact to update. The artifact_id field is required.
	Artifact      *Artifact `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArtifactRequest) Reset() {
	*x = UpdateArtifactRequest{}
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArtifactRequest) ProtoMessage() {}

func (x *UpdateArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArtifactRequest.ProtoReflect.Descriptor instead.
func (*UpdateArtifactRequest) Descriptor() ([]byte, []int) {
	return file_backend_api_v2beta1_artifact_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateArtifactRequest) GetArtifact() *Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

type GetArtifactRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The ID of the artifact to be retrieved.
	ArtifactId    string `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtifactRequest) Reset() {
	*x = GetArtifactRequest{}
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactRequest) ProtoMessage() {}

func (x *GetArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtifactRequest.ProtoReflect.Descriptor instead.
func (*GetArtifactRequest) Descriptor() ([]byte, []int) {
	return file_backend_api_v2beta1_artifact_proto_rawDescGZIP(), []int{2}
}

func (x *GetArtifactRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

type ListArtifactRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional input. Namespace for the artifacts.
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// A page token to request the results page.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// The number of artifacts to be listed per page. If there are more artifacts
	// than this number, the response message will contain a valid value in the
	// nextPageToken field.
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Sorting order in form of "field_name", "field_name asc" or "field_name desc".
	// Ascending by default.
	SortBy string `protobuf:"bytes,4,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	// A url-encoded, JSON-serialized filter protocol buffer (see
	// [filter.proto](https://github.com/kubeflow/artifacts/blob/master/backend/api/filter.proto)).
	Filter        string `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArtifactRequest) Reset() {
	*x = ListArtifactRequest{}
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactRequest) ProtoMessage() {}

func (x *ListArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtifactRequest.ProtoReflect.Descriptor instead.
func (*ListArtifactRequest) Descriptor() ([]byte, []int) {
	return file_backend_api_v2beta1_artifact_proto_rawDescGZIP(), []int{3}
}

func (x *ListArtifactRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListArtifactRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListArtifactRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListArtifactRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListArtifactRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type ListArtifactResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of artifacts returned.
	Artifacts []*Artifact `protobuf:"bytes,1,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	// The total number of artifacts available. This field is not always populated.
	TotalSize int32 `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	// A token to retrieve the next page of results, or empty if there are no
	// more results in the list.
	NextPageToken string `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArtifactResponse) Reset() {
	*x = ListArtifactResponse{}
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactResponse) ProtoMessage() {}

func (x *ListArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtifactResponse.ProtoReflect.Descriptor instead.
func (*ListArtifactResponse) Descriptor() ([]byte, []int) {
	return file_backend_api_v2beta1_artifact_proto_rawDescGZIP(), []int{4}
}

func (x *ListArtifactResponse) GetArtifacts() []*Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *ListArtifactResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *ListArtifactResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// The fields here work the same as previous backend api calls
type ListArtifactTasksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional, filter artifact task by a set of task_ids
	// We can also likely just rely on filter for this and omit this field
	TaskIds []string `protobuf:"bytes,1,rep,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	// Optional, filter artifact task by a set of run_ids
	RunIds []string `protobuf:"bytes,2,rep,name=run_ids,json=runIds,proto3" json:"run_ids,omitempty"`
	// Optional, filter artifact task by a set of artifact_ids
	// We can also likely just rely on filter for this and omit this field
	ArtifactIds []string `protobuf:"bytes,3,rep,name=artifact_ids,json=artifactIds,proto3" json:"artifact_ids,omitempty"`
	// Optional. Only list artifact tasks that have artifacts of this type.
	Type          ArtifactTaskType `protobuf:"varint,4,opt,name=type,proto3,enum=kubeflow.pipelines.backend.api.v2beta1.ArtifactTaskType" json:"type,omitempty"`
	PageToken     string           `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	PageSize      int32            `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBy        string           `protobuf:"bytes,7,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	Filter        string           `protobuf:"bytes,8,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArtifactTasksRequest) Reset() {
	*x = ListArtifactTasksRequest{}
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactTasksRequest) ProtoMessage() {}

func (x *ListArtifactTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtifactTasksRequest.ProtoReflect.Descriptor instead.
func (*ListArtifactTasksRequest) Descriptor() ([]byte, []int) {
	return file_backend_api_v2beta1_artifact_proto_rawDescGZIP(), []int{5}
}

func (x *ListArtifactTasksRequest) GetTaskIds() []string {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

func (x *ListArtifactTasksRequest) GetRunIds() []string {
	if x != nil {
		return x.RunIds
	}
	return nil
}

func (x *ListArtifactTasksRequest) GetArtifactIds() []string {
	if x != nil {
		return x.ArtifactIds
	}
	return nil
}

func (x *ListArtifactTasksRequest) GetType() ArtifactTaskType {
	if x != nil {
		return x.Type
	}
	return ArtifactTaskType_INPUT
}

func (x *ListArtifactTasksRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListArtifactTasksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListArtifactTasksRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListArtifactTasksRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type ListArtifactTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactTasks []*ArtifactTask        `protobuf:"bytes,1,rep,name=artifact_tasks,json=artifactTasks,proto3" json:"artifact_tasks,omitempty"`
	TotalSize     int32                  `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	NextPageToken string                 `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArtifactTasksResponse) Reset() {
	*x = ListArtifactTasksResponse{}
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactTasksResponse) ProtoMessage() {}

func (x *ListArtifactTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtifactTasksResponse.ProtoReflect.Descriptor instead.
func (*ListArtifactTasksResponse) Descriptor() ([]byte, []int) {
	return file_backend_api_v2beta1_artifact_proto_rawDescGZIP(), []int{6}
}

func (x *ListArtifactTasksResponse) GetArtifactTasks() []*ArtifactTask {
	if x != nil {
		return x.ArtifactTasks
	}
	return nil
}

func (x *ListArtifactTasksResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *ListArtifactTasksResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Request to create an artifact-task relationship
type CreateArtifactTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The artifact-task relationship to create.
	ArtifactTask  *ArtifactTask `protobuf:"bytes,1,opt,name=artifact_task,json=artifactTask,proto3" json:"artifact_task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArtifactTaskRequest) Reset() {
	*x = CreateArtifactTaskRequest{}
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArtifactTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArtifactTaskRequest) ProtoMessage() {}

func (x *CreateArtifactTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArtifactTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateArtifactTaskRequest) Descriptor() ([]byte, []int) {
	return file_backend_api_v2beta1_artifact_proto_rawDescGZIP(), []int{7}
}

func (x *CreateArtifactTaskRequest) GetArtifactTask() *ArtifactTask {
	if x != nil {
		return x.ArtifactTask
	}
	return nil
}

type LogMetricRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The metric to log.
	Metric        *Metric `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogMetricRequest) Reset() {
	*x = LogMetricRequest{}
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMetricRequest) ProtoMessage() {}

func (x *LogMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMetricRequest.ProtoReflect.Descriptor instead.
func (*LogMetricRequest) Descriptor() ([]byte, []int) {
	return file_backend_api_v2beta1_artifact_proto_rawDescGZIP(), []int{8}
}

func (x *LogMetricRequest) GetMetric() *Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

type GetMetricRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Task UUID that owns this metric
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Required. Name of the metric
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricRequest) Reset() {
	*x = GetMetricRequest{}
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricRequest) ProtoMessage() {}

func (x *GetMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricRequest.ProtoReflect.Descriptor instead.
func (*GetMetricRequest) Descriptor() ([]byte, []int) {
	return file_backend_api_v2beta1_artifact_proto_rawDescGZIP(), []int{9}
}

func (x *GetMetricRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetMetricRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListMetricsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional, filter metrics by a set of task_ids
	TaskIds []string `protobuf:"bytes,1,rep,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	// Optional, filter metrics by a set of run_ids
	RunIds []string `protobuf:"bytes,2,rep,name=run_ids,json=runIds,proto3" json:"run_ids,omitempty"`
	// Optional. Namespace for the metrics.
	Namespace string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// A page token to request the results page.
	PageToken string `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// The number of metrics to be listed per page.
	PageSize int32 `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Sorting order in form of "field_name", "field_name asc" or "field_name desc".
	SortBy string `protobuf:"bytes,6,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	// A url-encoded, JSON-serialized filter protocol buffer.
	Filter        string `protobuf:"bytes,7,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMetricsRequest) Reset() {
	*x = ListMetricsRequest{}
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMetricsRequest) ProtoMessage() {}

func (x *ListMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMetricsRequest.ProtoReflect.Descriptor instead.
func (*ListMetricsRequest) Descriptor() ([]byte, []int) {
	return file_backend_api_v2beta1_artifact_proto_rawDescGZIP(), []int{10}
}

func (x *ListMetricsRequest) GetTaskIds() []string {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

func (x *ListMetricsRequest) GetRunIds() []string {
	if x != nil {
		return x.RunIds
	}
	return nil
}

func (x *ListMetricsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListMetricsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListMetricsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListMetricsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListMetricsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type ListMetricsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of metrics returned.
	Metrics []*Metric `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	// The total number of metrics available.
	TotalSize int32 `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	// Token to retrieve the next page of results.
	NextPageToken string `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMetricsResponse) Reset() {
	*x = ListMetricsResponse{}
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMetricsResponse) ProtoMessage() {}

func (x *ListMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMetricsResponse.ProtoReflect.Descriptor instead.
func (*ListMetricsResponse) Descriptor() ([]byte, []int) {
	return file_backend_api_v2beta1_artifact_proto_rawDescGZIP(), []int{11}
}

func (x *ListMetricsResponse) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *ListMetricsResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *ListMetricsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ArtifactTask struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output only. The unique server generated id of the ArtifactTask.
	Id            string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ArtifactId    string           `protobuf:"bytes,2,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	TaskId        string           `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Type          ArtifactTaskType `protobuf:"varint,4,opt,name=type,proto3,enum=kubeflow.pipelines.backend.api.v2beta1.ArtifactTaskType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactTask) Reset() {
	*x = ArtifactTask{}
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactTask) ProtoMessage() {}

func (x *ArtifactTask) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactTask.ProtoReflect.Descriptor instead.
func (*ArtifactTask) Descriptor() ([]byte, []int) {
	return file_backend_api_v2beta1_artifact_proto_rawDescGZIP(), []int{12}
}

func (x *ArtifactTask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ArtifactTask) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *ArtifactTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ArtifactTask) GetType() ArtifactTaskType {
	if x != nil {
		return x.Type
	}
	return ArtifactTaskType_INPUT
}

type Metric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Task UUID that owns this metric
	RunId string `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// Required. Task UUID that owns this metric
	TaskId string `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Required. Name of the metric
	Name   string        `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Schema Metric_Schema `protobuf:"varint,4,opt,name=schema,proto3,enum=kubeflow.pipelines.backend.api.v2beta1.Metric_Schema" json:"schema,omitempty"`
	// Value can be double or a valid json,
	// but not string_value, bool_value, null_value
	// API server validation will be needed
	Value     *structpb.Value        `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Type of the metric (input/output), defaults to input if not provided.
	Type          MetricType `protobuf:"varint,7,opt,name=type,proto3,enum=kubeflow.pipelines.backend.api.v2beta1.MetricType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_backend_api_v2beta1_artifact_proto_rawDescGZIP(), []int{13}
}

func (x *Metric) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Metric) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetSchema() Metric_Schema {
	if x != nil {
		return x.Schema
	}
	return Metric_Metric
}

func (x *Metric) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Metric) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Metric) GetType() MetricType {
	if x != nil {
		return x.Type
	}
	return MetricType_METRIC_INPUT
}

// Note to be confused with RuntimeArtifact in pipelinespec
type Artifact struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output only. The unique server generated id of the artifact.
	// Note: Updated id name to be consistent with other api naming patterns (with prefix)
	ArtifactId string `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	// Required. The client provided name of the artifact.
	// Note: it seems in MLMD when name was set, it had to be unique for that type_id
	// this restriction is removed here
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Required. The name of an ArtifactType. E.g. Dataset
	Type Artifact_ArtifactType `protobuf:"varint,3,opt,name=type,proto3,enum=kubeflow.pipelines.backend.api.v2beta1.Artifact_ArtifactType" json:"type,omitempty"`
	// Required. The uniform resource identifier of the physical artifact.
	// May be empty if there is no physical artifact.
	Uri string `protobuf:"bytes,4,opt,name=uri,proto3" json:"uri,omitempty"`
	// Optional. User provided custom properties which are not defined by its type.
	Metadata map[string]*structpb.Value `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Output only. Create time of the artifact in millisecond since epoch.
	// Note: The type and name is updated from mlmd artifact to be consistent with other backend apis.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Namespace     string                 `protobuf:"bytes,7,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_backend_api_v2beta1_artifact_proto_rawDescGZIP(), []int{14}
}

func (x *Artifact) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *Artifact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Artifact) GetType() Artifact_ArtifactType {
	if x != nil {
		return x.Type
	}
	return Artifact_Artifact
}

func (x *Artifact) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Artifact) GetMetadata() map[string]*structpb.Value {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Artifact) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Artifact) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

var File_backend_api_v2beta1_artifact_proto protoreflect.FileDescriptor

const file_backend_api_v2beta1_artifact_proto_rawDesc = "" +
	"\n" +
	"\"backend/api/v2beta1/artifact.proto\x12&kubeflow.pipelines.backend.api.v2beta1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"e\n" +
	"\x15CreateArtifactRequest\x12L\n" +
	"\bartifact\x18\x01 \x01(\v20.kubeflow.pipelines.backend.api.v2beta1.ArtifactR\bartifact\"e\n" +
	"\x15UpdateArtifactRequest\x12L\n" +
	"\bartifact\x18\x01 \x01(\v20.kubeflow.pipelines.backend.api.v2beta1.ArtifactR\bartifact\"5\n" +
	"\x12GetArtifactRequest\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\"\xa0\x01\n" +
	"\x13ListArtifactRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\x04 \x01(\tR\x06sortBy\x12\x16\n" +
	"\x06filter\x18\x05 \x01(\tR\x06filter\"\xad\x01\n" +
	"\x14ListArtifactResponse\x12N\n" +
	"\tartifacts\x18\x01 \x03(\v20.kubeflow.pipelines.backend.api.v2beta1.ArtifactR\tartifacts\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x05R\ttotalSize\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken\"\xac\x02\n" +
	"\x18ListArtifactTasksRequest\x12\x19\n" +
	"\btask_ids\x18\x01 \x03(\tR\ataskIds\x12\x17\n" +
	"\arun_ids\x18\x02 \x03(\tR\x06runIds\x12!\n" +
	"\fartifact_ids\x18\x03 \x03(\tR\vartifactIds\x12L\n" +
	"\x04type\x18\x04 \x01(\x0e28.kubeflow.pipelines.backend.api.v2beta1.ArtifactTaskTypeR\x04type\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\a \x01(\tR\x06sortBy\x12\x16\n" +
	"\x06filter\x18\b \x01(\tR\x06filter\"\xbf\x01\n" +
	"\x19ListArtifactTasksResponse\x12[\n" +
	"\x0eartifact_tasks\x18\x01 \x03(\v24.kubeflow.pipelines.backend.api.v2beta1.ArtifactTaskR\rartifactTasks\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x05R\ttotalSize\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken\"v\n" +
	"\x19CreateArtifactTaskRequest\x12Y\n" +
	"\rartifact_task\x18\x01 \x01(\v24.kubeflow.pipelines.backend.api.v2beta1.ArtifactTaskR\fartifactTask\"Z\n" +
	"\x10LogMetricRequest\x12F\n" +
	"\x06metric\x18\x01 \x01(\v2..kubeflow.pipelines.backend.api.v2beta1.MetricR\x06metric\"?\n" +
	"\x10GetMetricRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xd3\x01\n" +
	"\x12ListMetricsRequest\x12\x19\n" +
	"\btask_ids\x18\x01 \x03(\tR\ataskIds\x12\x17\n" +
	"\arun_ids\x18\x02 \x03(\tR\x06runIds\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\x06 \x01(\tR\x06sortBy\x12\x16\n" +
	"\x06filter\x18\a \x01(\tR\x06filter\"\xa6\x01\n" +
	"\x13ListMetricsResponse\x12H\n" +
	"\ametrics\x18\x01 \x03(\v2..kubeflow.pipelines.backend.api.v2beta1.MetricR\ametrics\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x05R\ttotalSize\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken\"\xa6\x01\n" +
	"\fArtifactTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vartifact_id\x18\x02 \x01(\tR\n" +
	"artifactId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12L\n" +
	"\x04type\x18\x04 \x01(\x0e28.kubeflow.pipelines.backend.api.v2beta1.ArtifactTaskTypeR\x04type\"\x9c\x03\n" +
	"\x06Metric\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12M\n" +
	"\x06schema\x18\x04 \x01(\x0e25.kubeflow.pipelines.backend.api.v2beta1.Metric.SchemaR\x06schema\x12,\n" +
	"\x05value\x18\x05 \x01(\v2\x16.google.protobuf.ValueR\x05value\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12F\n" +
	"\x04type\x18\a \x01(\x0e22.kubeflow.pipelines.backend.api.v2beta1.MetricTypeR\x04type\"N\n" +
	"\x06Schema\x12\n" +
	"\n" +
	"\x06Metric\x10\x00\x12\x18\n" +
	"\x14ClassificationMetric\x10\x01\x12\x1e\n" +
	"\x1aSlicedClassificationMetric\x10\x02\"\xfc\x03\n" +
	"\bArtifact\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12Q\n" +
	"\x04type\x18\x03 \x01(\x0e2=.kubeflow.pipelines.backend.api.v2beta1.Artifact.ArtifactTypeR\x04type\x12\x10\n" +
	"\x03uri\x18\x04 \x01(\tR\x03uri\x12Z\n" +
	"\bmetadata\x18\x05 \x03(\v2>.kubeflow.pipelines.backend.api.v2beta1.Artifact.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1c\n" +
	"\tnamespace\x18\a \x01(\tR\tnamespace\x1aS\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"L\n" +
	"\fArtifactType\x12\f\n" +
	"\bArtifact\x10\x00\x12\t\n" +
	"\x05Model\x10\x01\x12\v\n" +
	"\aDataset\x10\x02\x12\b\n" +
	"\x04HTML\x10\x03\x12\f\n" +
	"\bMarkdown\x10\x04*)\n" +
	"\x10ArtifactTaskType\x12\t\n" +
	"\x05INPUT\x10\x00\x12\n" +
	"\n" +
	"\x06OUTPUT\x10\x01*1\n" +
	"\n" +
	"MetricType\x12\x10\n" +
	"\fMETRIC_INPUT\x10\x00\x12\x11\n" +
	"\rMETRIC_OUTPUT\x10\x012\xbb\x11\n" +
	"\x0fArtifactService\x12\x84\x02\n" +
	"\rListArtifacts\x12;.kubeflow.pipelines.backend.api.v2beta1.ListArtifactRequest\x1a<.kubeflow.pipelines.backend.api.v2beta1.ListArtifactResponse\"x\x92AV\n" +
	"\x0fArtifactService\x123Finds all artifacts within the specified namespace.*\x0elist_artifacts\x82\xd3\xe4\x93\x02\x19\x12\x17/apis/v2beta1/artifacts\x12\xee\x01\n" +
	"\vGetArtifact\x12:.kubeflow.pipelines.backend.api.v2beta1.GetArtifactRequest\x1a0.kubeflow.pipelines.backend.api.v2beta1.Artifact\"q\x92AA\n" +
	"\x0fArtifactService\x12 Finds a specific Artifact by ID.*\fget_artifact\x82\xd3\xe4\x93\x02'\x12%/apis/v2beta1/artifacts/{artifact_id}\x12\x88\x02\n" +
	"\x0eUpdateArtifact\x12=.kubeflow.pipelines.backend.api.v2beta1.UpdateArtifactRequest\x1a0.kubeflow.pipelines.backend.api.v2beta1.Artifact\"\x84\x01\x92AA\n" +
	"\x0fArtifactService\x12\x1dUpdates an existing artifact.*\x0fupdate_artifact\x82\xd3\xe4\x93\x02::\bartifact\x1a./apis/v2beta1/artifacts/{artifact.artifact_id}\x12\x8b\x02\n" +
	"\x11ListArtifactTasks\x12@.kubeflow.pipelines.backend.api.v2beta1.ListArtifactTasksRequest\x1aA.kubeflow.pipelines.backend.api.v2beta1.ListArtifactTasksResponse\"q\x92AJ\n" +
	"\x0fArtifactService\x12\"Lists artifact-task relationships.*\x13list_artifact_tasks\x82\xd3\xe4\x93\x02\x1e\x12\x1c/apis/v2beta1/artifact_tasks\x12\x88\x02\n" +
	"\x12CreateArtifactTask\x12A.kubeflow.pipelines.backend.api.v2beta1.CreateArtifactTaskRequest\x1a4.kubeflow.pipelines.backend.api.v2beta1.ArtifactTask\"y\x92AO\n" +
	"\x0fArtifactService\x12&Creates an artifact-task relationship.*\x14create_artifact_task\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/apis/v2beta1/artifact_tasks\x12\xe3\x01\n" +
	"\x0eCreateArtifact\x12=.kubeflow.pipelines.backend.api.v2beta1.CreateArtifactRequest\x1a0.kubeflow.pipelines.backend.api.v2beta1.Artifact\"`\x92A;\n" +
	"\x0fArtifactService\x12\x17Creates a new artifact.*\x0fcreate_artifact\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/apis/v2beta1/artifacts\x12\xdb\x01\n" +
	"\tLogMetric\x128.kubeflow.pipelines.backend.api.v2beta1.LogMetricRequest\x1a..kubeflow.pipelines.backend.api.v2beta1.Metric\"d\x92AA\n" +
	"\x0fArtifactService\x12\"Logs a metric for a specific task.*\n" +
	"log_metric\x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/apis/v2beta1/metrics\x12\xe9\x01\n" +
	"\tGetMetric\x128.kubeflow.pipelines.backend.api.v2beta1.GetMetricRequest\x1a..kubeflow.pipelines.backend.api.v2beta1.Metric\"r\x92AA\n" +
	"\x0fArtifactService\x12\"Gets a metric by task ID and name.*\n" +
	"get_metric\x82\xd3\xe4\x93\x02(\x12&/apis/v2beta1/metrics/{task_id}/{name}\x12\xdb\x01\n" +
	"\vListMetrics\x12:.kubeflow.pipelines.backend.api.v2beta1.ListMetricsRequest\x1a;.kubeflow.pipelines.backend.api.v2beta1.ListMetricsResponse\"S\x92A3\n" +
	"\x0fArtifactService\x12\x12Lists all metrics.*\flist_metrics\x82\xd3\xe4\x93\x02\x17\x12\x15/apis/v2beta1/metricsB\x8a\x01\x92AJ*\x02\x01\x02R#\n" +
	"\adefault\x12\x18\x12\x16\n" +
	"\x14\x1a\x12.google.rpc.StatusZ\x1f\n" +
	"\x1d\n" +
	"\x06Bearer\x12\x13\b\x02\x1a\rAuthorization \x02Z;github.com/kubeflow/pipelines/backend/api/v2beta1/go_clientb\x06proto3"

var (
	file_backend_api_v2beta1_artifact_proto_rawDescOnce sync.Once
	file_backend_api_v2beta1_artifact_proto_rawDescData []byte
)

func file_backend_api_v2beta1_artifact_proto_rawDescGZIP() []byte {
	file_backend_api_v2beta1_artifact_proto_rawDescOnce.Do(func() {
		file_backend_api_v2beta1_artifact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_api_v2beta1_artifact_proto_rawDesc), len(file_backend_api_v2beta1_artifact_proto_rawDesc)))
	})
	return file_backend_api_v2beta1_artifact_proto_rawDescData
}

var file_backend_api_v2beta1_artifact_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_backend_api_v2beta1_artifact_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_backend_api_v2beta1_artifact_proto_goTypes = []any{
	(ArtifactTaskType)(0),             // 0: kubeflow.pipelines.backend.api.v2beta1.ArtifactTaskType
	(MetricType)(0),                   // 1: kubeflow.pipelines.backend.api.v2beta1.MetricType
	(Metric_Schema)(0),                // 2: kubeflow.pipelines.backend.api.v2beta1.Metric.Schema
	(Artifact_ArtifactType)(0),        // 3: kubeflow.pipelines.backend.api.v2beta1.Artifact.ArtifactType
	(*CreateArtifactRequest)(nil),     // 4: kubeflow.pipelines.backend.api.v2beta1.CreateArtifactRequest
	(*UpdateArtifactRequest)(nil),     // 5: kubeflow.pipelines.backend.api.v2beta1.UpdateArtifactRequest
	(*GetArtifactRequest)(nil),        // 6: kubeflow.pipelines.backend.api.v2beta1.GetArtifactRequest
	(*ListArtifactRequest)(nil),       // 7: kubeflow.pipelines.backend.api.v2beta1.ListArtifactRequest
	(*ListArtifactResponse)(nil),      // 8: kubeflow.pipelines.backend.api.v2beta1.ListArtifactResponse
	(*ListArtifactTasksRequest)(nil),  // 9: kubeflow.pipelines.backend.api.v2beta1.ListArtifactTasksRequest
	(*ListArtifactTasksResponse)(nil), // 10: kubeflow.pipelines.backend.api.v2beta1.ListArtifactTasksResponse
	(*CreateArtifactTaskRequest)(nil), // 11: kubeflow.pipelines.backend.api.v2beta1.CreateArtifactTaskRequest
	(*LogMetricRequest)(nil),          // 12: kubeflow.pipelines.backend.api.v2beta1.LogMetricRequest
	(*GetMetricRequest)(nil),          // 13: kubeflow.pipelines.backend.api.v2beta1.GetMetricRequest
	(*ListMetricsRequest)(nil),        // 14: kubeflow.pipelines.backend.api.v2beta1.ListMetricsRequest
	(*ListMetricsResponse)(nil),       // 15: kubeflow.pipelines.backend.api.v2beta1.ListMetricsResponse
	(*ArtifactTask)(nil),              // 16: kubeflow.pipelines.backend.api.v2beta1.ArtifactTask
	(*Metric)(nil),                    // 17: kubeflow.pipelines.backend.api.v2beta1.Metric
	(*Artifact)(nil),                  // 18: kubeflow.pipelines.backend.api.v2beta1.Artifact
	nil,                               // 19: kubeflow.pipelines.backend.api.v2beta1.Artifact.MetadataEntry
	(*structpb.Value)(nil),            // 20: google.protobuf.Value
	(*timestamppb.Timestamp)(nil),     // 21: google.protobuf.Timestamp
}
var file_backend_api_v2beta1_artifact_proto_depIdxs = []int32{
	18, // 0: kubeflow.pipelines.backend.api.v2beta1.CreateArtifactRequest.artifact:type_name -> kubeflow.pipelines.backend.api.v2beta1.Artifact
	18, // 1: kubeflow.pipelines.backend.api.v2beta1.UpdateArtifactRequest.artifact:type_name -> kubeflow.pipelines.backend.api.v2beta1.Artifact
	18, // 2: kubeflow.pipelines.backend.api.v2beta1.ListArtifactResponse.artifacts:type_name -> kubeflow.pipelines.backend.api.v2beta1.Artifact
	0,  // 3: kubeflow.pipelines.backend.api.v2beta1.ListArtifactTasksRequest.type:type_name -> kubeflow.pipelines.backend.api.v2beta1.ArtifactTaskType
	16, // 4: kubeflow.pipelines.backend.api.v2beta1.ListArtifactTasksResponse.artifact_tasks:type_name -> kubeflow.pipelines.backend.api.v2beta1.ArtifactTask
	16, // 5: kubeflow.pipelines.backend.api.v2beta1.CreateArtifactTaskRequest.artifact_task:type_name -> kubeflow.pipelines.backend.api.v2beta1.ArtifactTask
	17, // 6: kubeflow.pipelines.backend.api.v2beta1.LogMetricRequest.metric:type_name -> kubeflow.pipelines.backend.api.v2beta1.Metric
	17, // 7: kubeflow.pipelines.backend.api.v2beta1.ListMetricsResponse.metrics:type_name -> kubeflow.pipelines.backend.api.v2beta1.Metric
	0,  // 8: kubeflow.pipelines.backend.api.v2beta1.ArtifactTask.type:type_name -> kubeflow.pipelines.backend.api.v2beta1.ArtifactTaskType
	2,  // 9: kubeflow.pipelines.backend.api.v2beta1.Metric.schema:type_name -> kubeflow.pipelines.backend.api.v2beta1.Metric.Schema
	20, // 10: kubeflow.pipelines.backend.api.v2beta1.Metric.value:type_name -> google.protobuf.Value
	21, // 11: kubeflow.pipelines.backend.api.v2beta1.Metric.created_at:type_name -> google.protobuf.Timestamp
	1,  // 12: kubeflow.pipelines.backend.api.v2beta1.Metric.type:type_name -> kubeflow.pipelines.backend.api.v2beta1.MetricType
	3,  // 13: kubeflow.pipelines.backend.api.v2beta1.Artifact.type:type_name -> kubeflow.pipelines.backend.api.v2beta1.Artifact.ArtifactType
	19, // 14: kubeflow.pipelines.backend.api.v2beta1.Artifact.metadata:type_name -> kubeflow.pipelines.backend.api.v2beta1.Artifact.MetadataEntry
	21, // 15: kubeflow.pipelines.backend.api.v2beta1.Artifact.created_at:type_name -> google.protobuf.Timestamp
	20, // 16: kubeflow.pipelines.backend.api.v2beta1.Artifact.MetadataEntry.value:type_name -> google.protobuf.Value
	7,  // 17: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.ListArtifacts:input_type -> kubeflow.pipelines.backend.api.v2beta1.ListArtifactRequest
	6,  // 18: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.GetArtifact:input_type -> kubeflow.pipelines.backend.api.v2beta1.GetArtifactRequest
	5,  // 19: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.UpdateArtifact:input_type -> kubeflow.pipelines.backend.api.v2beta1.UpdateArtifactRequest
	9,  // 20: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.ListArtifactTasks:input_type -> kubeflow.pipelines.backend.api.v2beta1.ListArtifactTasksRequest
	11, // 21: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.CreateArtifactTask:input_type -> kubeflow.pipelines.backend.api.v2beta1.CreateArtifactTaskRequest
	4,  // 22: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.CreateArtifact:input_type -> kubeflow.pipelines.backend.api.v2beta1.CreateArtifactRequest
	12, // 23: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.LogMetric:input_type -> kubeflow.pipelines.backend.api.v2beta1.LogMetricRequest
	13, // 24: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.GetMetric:input_type -> kubeflow.pipelines.backend.api.v2beta1.GetMetricRequest
	14, // 25: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.ListMetrics:input_type -> kubeflow.pipelines.backend.api.v2beta1.ListMetricsRequest
	8,  // 26: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.ListArtifacts:output_type -> kubeflow.pipelines.backend.api.v2beta1.ListArtifactResponse
	18, // 27: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.GetArtifact:output_type -> kubeflow.pipelines.backend.api.v2beta1.Artifact
	18, // 28: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.UpdateArtifact:output_type -> kubeflow.pipelines.backend.api.v2beta1.Artifact
	10, // 29: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.ListArtifactTasks:output_type -> kubeflow.pipelines.backend.api.v2beta1.ListArtifactTasksResponse
	16, // 30: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.CreateArtifactTask:output_type -> kubeflow.pipelines.backend.api.v2beta1.ArtifactTask
	18, // 31: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.CreateArtifact:output_type -> kubeflow.pipelines.backend.api.v2beta1.Artifact
	17, // 32: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.LogMetric:output_type -> kubeflow.pipelines.backend.api.v2beta1.Metric
	17, // 33: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.GetMetric:output_type -> kubeflow.pipelines.backend.api.v2beta1.Metric
	15, // 34: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.ListMetrics:output_type -> kubeflow.pipelines.backend.api.v2beta1.ListMetricsResponse
	26, // [26:35] is the sub-list for method output_type
	17, // [17:26] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_backend_api_v2beta1_artifact_proto_init() }
func file_backend_api_v2beta1_artifact_proto_init() {
	if File_backend_api_v2beta1_artifact_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_api_v2beta1_artifact_proto_rawDesc), len(file_backend_api_v2beta1_artifact_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_api_v2beta1_artifact_proto_goTypes,
		DependencyIndexes: file_backend_api_v2beta1_artifact_proto_depIdxs,
		EnumInfos:         file_backend_api_v2beta1_artifact_proto_enumTypes,
		MessageInfos:      file_backend_api_v2beta1_artifact_proto_msgTypes,
	}.Build()
	File_backend_api_v2beta1_artifact_proto = out.File
	file_backend_api_v2beta1_artifact_proto_goTypes = nil
	file_backend_api_v2beta1_artifact_proto_depIdxs = nil
}
