apiVersion: kustomize.factory.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow

resources:
- pipelineversion-validating-webhook-config.yaml
- pipelineversion-mutating-webhook-config.yaml

configurations:
- params.yaml
