// Code generated by go-swagger; DO NOT EDIT.

package artifact_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// V2beta1MetricType  - METRIC_TYPE_UNSPECIFIED: default; treated as "not set"
// reject if unset.
//
// swagger:model v2beta1MetricType
type V2beta1MetricType string

func NewV2beta1MetricType(value V2beta1MetricType) *V2beta1MetricType {
	return &value
}

// Pointer returns a pointer to a freshly-allocated V2beta1MetricType.
func (m V2beta1MetricType) Pointer() *V2beta1MetricType {
	return &m
}

const (

	// V2beta1MetricTypeMETRICTYPEUNSPECIFIED captures enum value "METRIC_TYPE_UNSPECIFIED"
	V2beta1MetricTypeMETRICTYPEUNSPECIFIED V2beta1MetricType = "METRIC_TYPE_UNSPECIFIED"

	// V2beta1MetricTypeMETRICINPUT captures enum value "METRIC_INPUT"
	V2beta1MetricTypeMETRICINPUT V2beta1MetricType = "METRIC_INPUT"

	// V2beta1MetricTypeMETRICOUTPUT captures enum value "METRIC_OUTPUT"
	V2beta1MetricTypeMETRICOUTPUT V2beta1MetricType = "METRIC_OUTPUT"
)

// for schema
var v2beta1MetricTypeEnum []interface{}

func init() {
	var res []V2beta1MetricType
	if err := json.Unmarshal([]byte(`["METRIC_TYPE_UNSPECIFIED","METRIC_INPUT","METRIC_OUTPUT"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		v2beta1MetricTypeEnum = append(v2beta1MetricTypeEnum, v)
	}
}

func (m V2beta1MetricType) validateV2beta1MetricTypeEnum(path, location string, value V2beta1MetricType) error {
	if err := validate.EnumCase(path, location, value, v2beta1MetricTypeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this v2beta1 metric type
func (m V2beta1MetricType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateV2beta1MetricTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this v2beta1 metric type based on context it is used
func (m V2beta1MetricType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
