# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\nkfp_common\x1a\x1cgoogle/protobuf/struct.proto\"\xc6\x03\n\x12InputParameterSpec\x12W\n\x15task_output_parameter\x18\x01 \x01(\x0b\x32\x36.kfp_common.InputParameterSpec.TaskOutputParameterSpecH\x00\x12<\n\rruntime_value\x18\x02 \x01(\x0b\x32#.kfp_common.ValueOrRuntimeParameterH\x00\x12#\n\x19\x63omponent_input_parameter\x18\x03 \x01(\tH\x00\x12K\n\x11task_final_status\x18\x05 \x01(\x0b\x32..kfp_common.InputParameterSpec.TaskFinalStatusH\x00\x12%\n\x1dparameter_expression_selector\x18\x04 \x01(\t\x1aN\n\x17TaskOutputParameterSpec\x12\x15\n\rproducer_task\x18\x01 \x01(\t\x12\x1c\n\x14output_parameter_key\x18\x02 \x01(\t\x1a(\n\x0fTaskFinalStatus\x12\x15\n\rproducer_task\x18\x01 \x01(\tB\x06\n\x04kind\"\x9c\x01\n\x17ValueOrRuntimeParameter\x12/\n\x0e\x63onstant_value\x18\x01 \x01(\x0b\x32\x11.kfp_common.ValueB\x02\x18\x01H\x00\x12\x1b\n\x11runtime_parameter\x18\x02 \x01(\tH\x00\x12*\n\x08\x63onstant\x18\x03 \x01(\x0b\x32\x16.google.protobuf.ValueH\x00\x42\x07\n\x05value\"U\n\x05Value\x12\x13\n\tint_value\x18\x01 \x01(\x03H\x00\x12\x16\n\x0c\x64ouble_value\x18\x02 \x01(\x01H\x00\x12\x16\n\x0cstring_value\x18\x03 \x01(\tH\x00\x42\x07\n\x05value\"N\n\x17TaskOutputParameterSpec\x12\x15\n\rproducer_task\x18\x01 \x01(\t\x12\x1c\n\x14output_parameter_key\x18\x02 \x01(\tb\x06proto3')



_INPUTPARAMETERSPEC = DESCRIPTOR.message_types_by_name['InputParameterSpec']
_INPUTPARAMETERSPEC_TASKOUTPUTPARAMETERSPEC = _INPUTPARAMETERSPEC.nested_types_by_name['TaskOutputParameterSpec']
_INPUTPARAMETERSPEC_TASKFINALSTATUS = _INPUTPARAMETERSPEC.nested_types_by_name['TaskFinalStatus']
_VALUEORRUNTIMEPARAMETER = DESCRIPTOR.message_types_by_name['ValueOrRuntimeParameter']
_VALUE = DESCRIPTOR.message_types_by_name['Value']
_TASKOUTPUTPARAMETERSPEC = DESCRIPTOR.message_types_by_name['TaskOutputParameterSpec']
InputParameterSpec = _reflection.GeneratedProtocolMessageType('InputParameterSpec', (_message.Message,), {

  'TaskOutputParameterSpec' : _reflection.GeneratedProtocolMessageType('TaskOutputParameterSpec', (_message.Message,), {
    'DESCRIPTOR' : _INPUTPARAMETERSPEC_TASKOUTPUTPARAMETERSPEC,
    '__module__' : 'common_pb2'
    # @@protoc_insertion_point(class_scope:kfp_common.InputParameterSpec.TaskOutputParameterSpec)
    })
  ,

  'TaskFinalStatus' : _reflection.GeneratedProtocolMessageType('TaskFinalStatus', (_message.Message,), {
    'DESCRIPTOR' : _INPUTPARAMETERSPEC_TASKFINALSTATUS,
    '__module__' : 'common_pb2'
    # @@protoc_insertion_point(class_scope:kfp_common.InputParameterSpec.TaskFinalStatus)
    })
  ,
  'DESCRIPTOR' : _INPUTPARAMETERSPEC,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:kfp_common.InputParameterSpec)
  })
_sym_db.RegisterMessage(InputParameterSpec)
_sym_db.RegisterMessage(InputParameterSpec.TaskOutputParameterSpec)
_sym_db.RegisterMessage(InputParameterSpec.TaskFinalStatus)

ValueOrRuntimeParameter = _reflection.GeneratedProtocolMessageType('ValueOrRuntimeParameter', (_message.Message,), {
  'DESCRIPTOR' : _VALUEORRUNTIMEPARAMETER,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:kfp_common.ValueOrRuntimeParameter)
  })
_sym_db.RegisterMessage(ValueOrRuntimeParameter)

Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), {
  'DESCRIPTOR' : _VALUE,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:kfp_common.Value)
  })
_sym_db.RegisterMessage(Value)

TaskOutputParameterSpec = _reflection.GeneratedProtocolMessageType('TaskOutputParameterSpec', (_message.Message,), {
  'DESCRIPTOR' : _TASKOUTPUTPARAMETERSPEC,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:kfp_common.TaskOutputParameterSpec)
  })
_sym_db.RegisterMessage(TaskOutputParameterSpec)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VALUEORRUNTIMEPARAMETER.fields_by_name['constant_value']._options = None
  _VALUEORRUNTIMEPARAMETER.fields_by_name['constant_value']._serialized_options = b'\030\001'
  _INPUTPARAMETERSPEC._serialized_start=59
  _INPUTPARAMETERSPEC._serialized_end=513
  _INPUTPARAMETERSPEC_TASKOUTPUTPARAMETERSPEC._serialized_start=385
  _INPUTPARAMETERSPEC_TASKOUTPUTPARAMETERSPEC._serialized_end=463
  _INPUTPARAMETERSPEC_TASKFINALSTATUS._serialized_start=465
  _INPUTPARAMETERSPEC_TASKFINALSTATUS._serialized_end=505
  _VALUEORRUNTIMEPARAMETER._serialized_start=516
  _VALUEORRUNTIMEPARAMETER._serialized_end=672
  _VALUE._serialized_start=674
  _VALUE._serialized_end=759
  _TASKOUTPUTPARAMETERSPEC._serialized_start=385
  _TASKOUTPUTPARAMETERSPEC._serialized_end=463
# @@protoc_insertion_point(module_scope)
