// Code generated by go-swagger; DO NOT EDIT.

package run_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// PipelineTaskDetailInputType pipeline task detail input type
//
// swagger:model PipelineTaskDetailInputType
type PipelineTaskDetailInputType string

func NewPipelineTaskDetailInputType(value PipelineTaskDetailInputType) *PipelineTaskDetailInputType {
	return &value
}

// Pointer returns a pointer to a freshly-allocated PipelineTaskDetailInputType.
func (m PipelineTaskDetailInputType) Pointer() *PipelineTaskDetailInputType {
	return &m
}

const (

	// PipelineTaskDetailInputTypeResolvedValue captures enum value "ResolvedValue"
	PipelineTaskDetailInputTypeResolvedValue PipelineTaskDetailInputType = "ResolvedValue"

	// PipelineTaskDetailInputTypePipelineChannel captures enum value "PipelineChannel"
	PipelineTaskDetailInputTypePipelineChannel PipelineTaskDetailInputType = "PipelineChannel"
)

// for schema
var pipelineTaskDetailInputTypeEnum []interface{}

func init() {
	var res []PipelineTaskDetailInputType
	if err := json.Unmarshal([]byte(`["ResolvedValue","PipelineChannel"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		pipelineTaskDetailInputTypeEnum = append(pipelineTaskDetailInputTypeEnum, v)
	}
}

func (m PipelineTaskDetailInputType) validatePipelineTaskDetailInputTypeEnum(path, location string, value PipelineTaskDetailInputType) error {
	if err := validate.EnumCase(path, location, value, pipelineTaskDetailInputTypeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this pipeline task detail input type
func (m PipelineTaskDetailInputType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validatePipelineTaskDetailInputTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this pipeline task detail input type based on context it is used
func (m PipelineTaskDetailInputType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
