// Code generated by go-swagger; DO NOT EDIT.

package run_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// V2beta1MetricSchema Required. Schema of the metric
//
// swagger:model v2beta1MetricSchema
type V2beta1MetricSchema string

func NewV2beta1MetricSchema(value V2beta1MetricSchema) *V2beta1MetricSchema {
	return &value
}

// Pointer returns a pointer to a freshly-allocated V2beta1MetricSchema.
func (m V2beta1MetricSchema) Pointer() *V2beta1MetricSchema {
	return &m
}

const (

	// V2beta1MetricSchemaMetric captures enum value "Metric"
	V2beta1MetricSchemaMetric V2beta1MetricSchema = "Metric"

	// V2beta1MetricSchemaClassificationMetric captures enum value "ClassificationMetric"
	V2beta1MetricSchemaClassificationMetric V2beta1MetricSchema = "ClassificationMetric"

	// V2beta1MetricSchemaSlicedClassificationMetric captures enum value "SlicedClassificationMetric"
	V2beta1MetricSchemaSlicedClassificationMetric V2beta1MetricSchema = "SlicedClassificationMetric"
)

// for schema
var v2beta1MetricSchemaEnum []interface{}

func init() {
	var res []V2beta1MetricSchema
	if err := json.Unmarshal([]byte(`["Metric","ClassificationMetric","SlicedClassificationMetric"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		v2beta1MetricSchemaEnum = append(v2beta1MetricSchemaEnum, v)
	}
}

func (m V2beta1MetricSchema) validateV2beta1MetricSchemaEnum(path, location string, value V2beta1MetricSchema) error {
	if err := validate.EnumCase(path, location, value, v2beta1MetricSchemaEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this v2beta1 metric schema
func (m V2beta1MetricSchema) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateV2beta1MetricSchemaEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this v2beta1 metric schema based on context it is used
func (m V2beta1MetricSchema) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
