apiVersion: kustomize.factory.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
configMapGenerator:
- envs:
  - params.env
  name: pipeline-api-server-factory
