// Code generated by go-swagger; DO NOT EDIT.

package artifact_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetMetricParams creates a new GetMetricParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMetricParams() *GetMetricParams {
	return &GetMetricParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMetricParamsWithTimeout creates a new GetMetricParams object
// with the ability to set a timeout on a request.
func NewGetMetricParamsWithTimeout(timeout time.Duration) *GetMetricParams {
	return &GetMetricParams{
		timeout: timeout,
	}
}

// NewGetMetricParamsWithContext creates a new GetMetricParams object
// with the ability to set a context for a request.
func NewGetMetricParamsWithContext(ctx context.Context) *GetMetricParams {
	return &GetMetricParams{
		Context: ctx,
	}
}

// NewGetMetricParamsWithHTTPClient creates a new GetMetricParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMetricParamsWithHTTPClient(client *http.Client) *GetMetricParams {
	return &GetMetricParams{
		HTTPClient: client,
	}
}

/*
GetMetricParams contains all the parameters to send to the API endpoint

	for the get metric operation.

	Typically these are written to a http.Request.
*/
type GetMetricParams struct {

	/* Name.

	   Required. Name of the metric
	*/
	Name string

	/* TaskID.

	   Required. Task UUID that owns this metric
	*/
	TaskID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get metric params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMetricParams) WithDefaults() *GetMetricParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get metric params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMetricParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get metric params
func (o *GetMetricParams) WithTimeout(timeout time.Duration) *GetMetricParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get metric params
func (o *GetMetricParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get metric params
func (o *GetMetricParams) WithContext(ctx context.Context) *GetMetricParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get metric params
func (o *GetMetricParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get metric params
func (o *GetMetricParams) WithHTTPClient(client *http.Client) *GetMetricParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get metric params
func (o *GetMetricParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get metric params
func (o *GetMetricParams) WithName(name string) *GetMetricParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get metric params
func (o *GetMetricParams) SetName(name string) {
	o.Name = name
}

// WithTaskID adds the taskID to the get metric params
func (o *GetMetricParams) WithTaskID(taskID string) *GetMetricParams {
	o.SetTaskID(taskID)
	return o
}

// SetTaskID adds the taskId to the get metric params
func (o *GetMetricParams) SetTaskID(taskID string) {
	o.TaskID = taskID
}

// WriteToRequest writes these params to a swagger request
func (o *GetMetricParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param task_id
	if err := r.SetPathParam("task_id", o.TaskID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
