// Code generated by go-swagger; DO NOT EDIT.

package artifact_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/kubeflow/pipelines/backend/api/v2beta1/go_http_client/artifact_model"
)

// UpdateArtifactReader is a Reader for the UpdateArtifact structure.
type UpdateArtifactReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateArtifactReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateArtifactOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewUpdateArtifactDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateArtifactOK creates a UpdateArtifactOK with default headers values
func NewUpdateArtifactOK() *UpdateArtifactOK {
	return &UpdateArtifactOK{}
}

/*
UpdateArtifactOK describes a response with status code 200, with default header values.

A successful response.
*/
type UpdateArtifactOK struct {
	Payload *artifact_model.V2beta1Artifact
}

// IsSuccess returns true when this update artifact o k response has a 2xx status code
func (o *UpdateArtifactOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update artifact o k response has a 3xx status code
func (o *UpdateArtifactOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update artifact o k response has a 4xx status code
func (o *UpdateArtifactOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update artifact o k response has a 5xx status code
func (o *UpdateArtifactOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update artifact o k response a status code equal to that given
func (o *UpdateArtifactOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update artifact o k response
func (o *UpdateArtifactOK) Code() int {
	return 200
}

func (o *UpdateArtifactOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /apis/v2beta1/artifacts/{artifact.artifact_id}][%d] updateArtifactOK %s", 200, payload)
}

func (o *UpdateArtifactOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /apis/v2beta1/artifacts/{artifact.artifact_id}][%d] updateArtifactOK %s", 200, payload)
}

func (o *UpdateArtifactOK) GetPayload() *artifact_model.V2beta1Artifact {
	return o.Payload
}

func (o *UpdateArtifactOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(artifact_model.V2beta1Artifact)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateArtifactDefault creates a UpdateArtifactDefault with default headers values
func NewUpdateArtifactDefault(code int) *UpdateArtifactDefault {
	return &UpdateArtifactDefault{
		_statusCode: code,
	}
}

/*
UpdateArtifactDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type UpdateArtifactDefault struct {
	_statusCode int

	Payload *artifact_model.GooglerpcStatus
}

// IsSuccess returns true when this update artifact default response has a 2xx status code
func (o *UpdateArtifactDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this update artifact default response has a 3xx status code
func (o *UpdateArtifactDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this update artifact default response has a 4xx status code
func (o *UpdateArtifactDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this update artifact default response has a 5xx status code
func (o *UpdateArtifactDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this update artifact default response a status code equal to that given
func (o *UpdateArtifactDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the update artifact default response
func (o *UpdateArtifactDefault) Code() int {
	return o._statusCode
}

func (o *UpdateArtifactDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /apis/v2beta1/artifacts/{artifact.artifact_id}][%d] update_artifact default %s", o._statusCode, payload)
}

func (o *UpdateArtifactDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /apis/v2beta1/artifacts/{artifact.artifact_id}][%d] update_artifact default %s", o._statusCode, payload)
}

func (o *UpdateArtifactDefault) GetPayload() *artifact_model.GooglerpcStatus {
	return o.Payload
}

func (o *UpdateArtifactDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(artifact_model.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
UpdateArtifactBody Required. The artifact to update. The artifact_id field is required.
swagger:model UpdateArtifactBody
*/
type UpdateArtifactBody struct {

	// Output only. Create time of the artifact in millisecond since epoch.
	// Note: The type and name is updated from mlmd artifact to be consistent with other backend apis.
	// Read Only: true
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// Optional. User provided custom properties which are not defined by its type.
	Metadata map[string]interface{} `json:"metadata,omitempty"`

	// Required. The client provided name of the artifact.
	// Note: it seems in MLMD when name was set, it had to be unique for that type_id
	// this restriction is removed here
	Name string `json:"name,omitempty"`

	// namespace
	Namespace string `json:"namespace,omitempty"`

	// Required. The name of an ArtifactType. E.g. Dataset
	Type *artifact_model.ArtifactArtifactType `json:"type,omitempty"`

	// Required. The uniform resource identifier of the physical artifact.
	// May be empty if there is no physical artifact.
	URI string `json:"uri,omitempty"`
}

// Validate validates this update artifact body
func (o *UpdateArtifactBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateArtifactBody) validateCreatedAt(formats strfmt.Registry) error {
	if swag.IsZero(o.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("artifact"+"."+"created_at", "body", "date-time", o.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *UpdateArtifactBody) validateType(formats strfmt.Registry) error {
	if swag.IsZero(o.Type) { // not required
		return nil
	}

	if o.Type != nil {
		if err := o.Type.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("artifact" + "." + "type")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("artifact" + "." + "type")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this update artifact body based on the context it is used
func (o *UpdateArtifactBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateCreatedAt(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateArtifactBody) contextValidateCreatedAt(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "artifact"+"."+"created_at", "body", strfmt.DateTime(o.CreatedAt)); err != nil {
		return err
	}

	return nil
}

func (o *UpdateArtifactBody) contextValidateType(ctx context.Context, formats strfmt.Registry) error {

	if o.Type != nil {

		if swag.IsZero(o.Type) { // not required
			return nil
		}

		if err := o.Type.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("artifact" + "." + "type")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("artifact" + "." + "type")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *UpdateArtifactBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateArtifactBody) UnmarshalBinary(b []byte) error {
	var res UpdateArtifactBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
