// Code generated by go-swagger; DO NOT EDIT.

package artifact_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateArtifactParams creates a new UpdateArtifactParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateArtifactParams() *UpdateArtifactParams {
	return &UpdateArtifactParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateArtifactParamsWithTimeout creates a new UpdateArtifactParams object
// with the ability to set a timeout on a request.
func NewUpdateArtifactParamsWithTimeout(timeout time.Duration) *UpdateArtifactParams {
	return &UpdateArtifactParams{
		timeout: timeout,
	}
}

// NewUpdateArtifactParamsWithContext creates a new UpdateArtifactParams object
// with the ability to set a context for a request.
func NewUpdateArtifactParamsWithContext(ctx context.Context) *UpdateArtifactParams {
	return &UpdateArtifactParams{
		Context: ctx,
	}
}

// NewUpdateArtifactParamsWithHTTPClient creates a new UpdateArtifactParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateArtifactParamsWithHTTPClient(client *http.Client) *UpdateArtifactParams {
	return &UpdateArtifactParams{
		HTTPClient: client,
	}
}

/*
UpdateArtifactParams contains all the parameters to send to the API endpoint

	for the update artifact operation.

	Typically these are written to a http.Request.
*/
type UpdateArtifactParams struct {

	/* Artifact.

	   Required. The artifact to update. The artifact_id field is required.
	*/
	Artifact UpdateArtifactBody

	/* ArtifactArtifactID.

	     Output only. The unique server generated id of the artifact.
	Note: Updated id name to be consistent with other api naming patterns (with prefix)
	*/
	ArtifactArtifactID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update artifact params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateArtifactParams) WithDefaults() *UpdateArtifactParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update artifact params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateArtifactParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update artifact params
func (o *UpdateArtifactParams) WithTimeout(timeout time.Duration) *UpdateArtifactParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update artifact params
func (o *UpdateArtifactParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update artifact params
func (o *UpdateArtifactParams) WithContext(ctx context.Context) *UpdateArtifactParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update artifact params
func (o *UpdateArtifactParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update artifact params
func (o *UpdateArtifactParams) WithHTTPClient(client *http.Client) *UpdateArtifactParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update artifact params
func (o *UpdateArtifactParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArtifact adds the artifact to the update artifact params
func (o *UpdateArtifactParams) WithArtifact(artifact UpdateArtifactBody) *UpdateArtifactParams {
	o.SetArtifact(artifact)
	return o
}

// SetArtifact adds the artifact to the update artifact params
func (o *UpdateArtifactParams) SetArtifact(artifact UpdateArtifactBody) {
	o.Artifact = artifact
}

// WithArtifactArtifactID adds the artifactArtifactID to the update artifact params
func (o *UpdateArtifactParams) WithArtifactArtifactID(artifactArtifactID string) *UpdateArtifactParams {
	o.SetArtifactArtifactID(artifactArtifactID)
	return o
}

// SetArtifactArtifactID adds the artifactArtifactId to the update artifact params
func (o *UpdateArtifactParams) SetArtifactArtifactID(artifactArtifactID string) {
	o.ArtifactArtifactID = artifactArtifactID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateArtifactParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Artifact); err != nil {
		return err
	}

	// path param artifact.artifact_id
	if err := r.SetPathParam("artifact.artifact_id", o.ArtifactArtifactID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
