name: KFP SDK Tests

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - 'api/**'
      - 'sdk/**'
      - 'test/presubmit-tests-sdk.sh'
      - '.github/workflows/kfp-sdk-tests.yml'
      - '!**/*.md'
      - '!**/OWNERS'

jobs:
  sdk-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.13']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install protobuf dependencies & kfp-pipeline-spec
      id: install-protobuf-deps
      uses: ./.github/actions/protobuf

    - name: Run SDK Tests
      run: |
        ./test/presubmit-tests-sdk.sh
