apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /prometheus-factory
  name: prometheus-factory
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|prometheus-factory'
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'argo'
        static_configs:
          - targets: ['workflow-controller-metrics:9090', 'argo-server:2746']
